### ISSUE TITLE
include prokaryotic names (e.g., from LPSN) as a source in the verifier

### ISSUE THREAD

**Issue by cpauvert** [gnames/gnverifier#109]
Hello, 
I just discovered `gnverfier` and the Global Names Architecture, thanks for these initiatives. The fact that it could work with OpenRefine is also a very nice development.

In my research institute, we are interested in microorganisms especially bacteria (:microbe:), where I also thought of having a verifier system like `gnverifier`. 

Are additional data sources considered for the  Global Names Architecture? 

If yes, I would suggest to include the [List of Prokaryotic names with Standing in Nomenclature](https://lpsn.dsmz.de/), for which there is an API and daily dumps (with registration though).

Best,

**Comment by cpauvert** [comment]
Awesome, thanks @dimus for your quick reply. Do not hesitate to ping once you do, so that I can try it out and point my microbiologists colleague to your resource as well!

**Comment by dimus** [comment]
@cpauvert I added LPSN, if you find any problems, please reopen the ticket and let me know

**Comment by cpauvert** [comment]
Hi @dimus 
Thanks for the quick implementation! 

I tried out with [_Bacteroides vulgatus_](https://lpsn.dsmz.de/species/bacteroides-vulgatus) expecting to be properly corrected to [_Phocaeicola vulgatus_](https://lpsn.dsmz.de/species/phocaeicola-vulgatus) as per the LPSN indication, but I was not...

https://verifier.globalnames.org/?capitalize=on&format=tsv&names=Bacteroides+vulgatus

Until I realized that the match to the LPSN did appear if I ticked the "Show all matches"

https://verifier.globalnames.org/?all_matches=on&capitalize=on&format=tsv&names=Bacteroides+vulgatus

It's just that the LPSN score was slightly lower 9.41496 vs 9.41391. Any reason for a difference in score when the match were essentially the same?

BEst, 

PS: can't wait to try this out with openrefine!!

**Comment by dimus** [comment]
@cpauvert sure, you welcime!

You can also try to limit searches:

![image](https://github.com/gnames/gnverifier/assets/12124/61eedfad-e934-4eb4-868b-b736bf60a558)


It would add a filter `ds=208` (to only show data from this data-source) to the query:

https://verifier.globalnames.org/?capitalize=on&ds=208&format=html&names=Bacteroides+vulgatus+

**Comment by craynaud007** [comment]
Hello @dimus,

I work with @cpauvert and I just tested gnverfier with OpenRefine, thanks for this initiative.
While using it I encounter some issues. First, I tried to select the LPSN data source as explain in [“Reconciling taxonomic names in OpenRefine via Global Names” ](https://github.com/gnames/gnverifier/wiki/OpenRefine-readme#filters-to-remove-false-positive-matches) and it work but partially. In fact, some species that were not in the LPSN, had a match according to another data source even if I specified to use only LPSN. **So, the question is how can I restrict to one data source on OpenRefine?**

The second problem I encountered was due to Current Name. As an example, I reconciled Bacteroides vulgatus and it gave me Bacteroides vulgatus Eggerth and Gagnon 1933. And if I look deeper in it, it is said that the current Name is Phocaeicola vulgatus (cf. screenshot). **So, the question is how can I say I only want the current name and not the older one?**

![image](https://github.com/gnames/gnverifier/assets/154422986/d0ba1f0a-94bb-42d4-9b62-b58716d650f0)

Best Regards
