### ISSUE TITLE
Unexpected match with or without ','

### ISSUE THREAD

**Issue by BenMerSci** [gnames/gnverifier#124]
When querrying for 'Cyprinus carpio' and adding the authorship to the query, the result vary whether there is a comma (,) or not:

`Cyprinus carpio linnaeus, 1758` (with the comma) returns what I would say the expected results:

`https://verifier.globalnames.org/api/v1/verifications/cyprinus+carpio+linnaeus%2C+1758?capitalize=true&all_matches=true&data_sources=1%7C3%7C147` 

which is one match for COL and one match ITIS, both `exact` match to the species level.

Now if we querry for the same information but without the comma between linnaeus and the year:

`Cyprinus carpio linnaeus 1758`:

`https://verifier.globalnames.org/api/v1/verifications/cyprinus+carpio+linnaeus+1758?capitalize=true&all_matches=true&data_sources=1%7C3%7C147`

we get two results again, one for COL and for ITIS, but both are `partialExact` and match to the genus level which i believe would not be the desired behaviour.

**Comment by dimus** [comment]
Thank you @BenMerSci, hm, we migrated the system, may be something did not go right, I will try to fix it asap

**Comment by dimus** [comment]
Please take in account that author has to be capitalized, otherwise parser will conisder it an infraspecific epithet.

https://parser.globalnames.org/?format=html&names=Cyprinus+carpio+linnaeus+1758&with_details=on

**Comment by dimus** [comment]
It does look like a standard behavior @BenMerSci, the difference is in parsing:

https://parser.globalnames.org/?format=html&names=Cyprinus+carpio+linnaeus%2C+1758%0D%0ACyprinus+carpio+linnaeus+1758&with_details=on

In the first case comma excludes `linnaeus` from name, because infraspecific epithets should not be followed by a comma in 'normal' scientific names. In the second case, without a comma, `linnaeus` follows expected pattern for an infraspecific epithet. If authors were capitalized, all should behave normally. 

Capitalization flag only works on the first character of a name, it does not try to figure out how everything else is capitalized. The reason I added it was mostly web UI, people often don't bother to capitalize genus, and most scientific names (except ones with hybrid sign at the beginning) start with capitalized letter.

**Comment by BenMerSci** [comment]
How does this work for example when an authorship has a lowercase prefix like `von Siebold` or `de Claireville` where the prefix is supposed to be written lowercase?

**Comment by BenMerSci** [comment]
I have to say it probably does not happen often that the authorship begins with lowercase prefix, so might not  be worth it.
I will make sure to capitalize the authorship from now on!
Thank you again @dimus for the quick feedback!
We can probably close the issue

**Comment by dimus** [comment]
Actually low case prefixes is a know issue, and they should be covered by the parser. so names like 

https://parser.globalnames.org/?format=html&names=Abella+von+Heyden%2C+1826&with_details=on

should be parsed correctly, if not, it would be a bug.
