### ISSUE TITLE
resolver vs verifier APIs: user defined IDs and request-response array order

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnverifier#63]
I am playing with the verifier api you mentioned in [#62](https://github.com/gnames/gnverifier/issues/62#issuecomment-974720476), 

> GNverifier is a faster version of resolver.globalnames.org and it has its own api:
> https://apidoc.globalnames.org/gnames

I see a major difference with https://resolver.globalnames.org/api
In resolver, as suggested in documentation, I was adding an id for each of the names in my list:
```
my-id-1|Parus major
my-id-2|Corvus corax
my-id-2|Ciconia ciconia
...
```
I suppose those ids were necessary because there is no guarantee that the results array will be sorted in the same order as the requested names. Correct? Or perhaps they were not strictly necessary because order was guaranteed anyway? 

In https://apidoc.globalnames.org/gnames I don't see an option for setting these identifiers anymore.

Does this mean the order in the verifier API response is guaranteed to match the same order of names sent in request? (using either GET or POST methods)

> resolver.globalnames.org is going to be retired somewhere in 2023 or the end of 2022.

Although I am still starting to use these APIs, it looks like resolver has many more optional parameters than verifier.
`with_context`, `with_vernaculars`, `with_canonical_ranks`
Are these going to be present in verifier as well?  Or just going to be removed because nobody uses them?

Thanks

**Comment by dimus** [comment]
@abubelinha, good points

1. You are right, the ID is removed because the order of results in `gnames` API query is guaranteed. I should add it to the documentation. Howerver, in gnverifier command line app, if more than 5000 names are processed in a file, the order of 5000 chunks is random by default. If order is important in gnverifier, the app has to run using 1 job. I think for most of the usecases a name-string is an OK ID by itself, so I decided to remove a minor inconvenience of inventing ID for every verified name.
2. Yes, not all options are moved to gnames yet. I am not going to retire resolver and http://gni.globalnames.org until the functionality of gnames/gnverifier is compatible. I am adding `with_context` and faceted search (gni feature) to gnames as we speak, `with_vernaculars` will be added as well. The `with_canonical_ranks` option is outdated: before there was only one canonical form returning, now there are 3 -- full (with canonical ranks and hybrid signs for named hybrids), simple (without ranks, and hybrid signs only for hybrid formulas), stemmed with letters normalization and removed suffixes.

One thing I understood, I should not provide v1 for `gnames` API yet, to follow [semantic versioning](https://semver.org/) for API as well. So I am going to downgrade it to /api/v0 until `gnames`, `gnmatcher` and `gnverifier` reach stable v1 for their command line apps. My plan is to let resolver to exist for about a year after new system reaches v1.

`GNparser` already reached v1 in January 2021. So I am thinking to retire v0 API some time in 2022. When GNverifier & Co. have v1, I will start the process of retirement for GNI and Resolver. The reason of not keeping them running is simple. Every API requires human resources for maintenance, and I think it is better to spend my resources on making new systems better, than on trying to keep aging software from bugs, security risks and incompatibility with 'changing universe'.

**Comment by abubelinha** [comment]
Thanks @dimus 

So, POST api calls with thousands of names are safe without identifiers. That was it.

I am not interested in using any of the `with_xxx` options I mentioned. I just asked to be sure not to start using anything that is going to be removed. 

Thanks a lot !!

**Comment by abubelinha** [comment]
> When GNverifier & Co. have v1, I will start the process of retirement for GNI and Resolver

I suppose that GNI is [Global Name Index](http://gni.globalnames.org/) ... which I have just discovered and looks very interesting.
Do I need to credentials to use its API? 
The [Help](https://wiki.github.com/dimus/gni/global-names-index-help) and [API](https://wiki.github.com/dimus/gni/api) links in the top right both lead me to an "invalid request" pages, but it might be because I have not created an account.

**Comment by dimus** [comment]
GNI is the very first take to make a verification for Global Names from about 13 years ago. Its database is not updated, and its code runs on ancient acrhitectures. I might need to 'sunset' it earlier just because of something like a hardware failure. So please use it with caution and understanding that it might disappear suddenly. I am implementing faceted search for `gnames` this week ( which will also have abbreviated genus feature).
