### ISSUE TITLE
Outlinks to CoL when isSynonym: true return 404

### ISSUE THREAD

**Issue by dshorthouse** [gnames/gnverifier#74]
When `isSynonym = true` for Catalogue of Life responses, the `outlink` returns a 404 at their end.

Example: https://verifier.globalnames.org/api/v0/search/n:Pomatomus+saltator+ds:1

...provides the outlink: https://www.catalogueoflife.org/data/taxon/4LQWB. The taxon at 4LQWB has evidently disappeared.

The issue is squarely at CoL's end, but this makes for a less desirable outcome for integration. cc @mdoering @gdower @cgendreau

**Comment by mdoering** [comment]
Interesting. I cannot immediately see when that identifier was coined though.
The new COL IDs were first created with the December 2020 release. For `Pomatomus saltatrix (Linnaeus, 1766)` this was `4LQWC`, not `4LQWB` as you can see from the links below which represent all releases since 12-2020:

https://api.catalogueoflife.org/dataset/2242/taxon/4LQWC
https://api.catalogueoflife.org/dataset/2296/taxon/4LQWC
https://api.catalogueoflife.org/dataset/2303/taxon/4LQWC
https://api.catalogueoflife.org/dataset/2315/taxon/4LQWC
https://api.catalogueoflife.org/dataset/2328/taxon/4LQWC
https://api.catalogueoflife.org/dataset/2332/taxon/4LQWC
https://api.catalogueoflife.org/dataset/2344/taxon/4LQWC
https://api.catalogueoflife.org/dataset/2349/taxon/4LQWC
https://api.catalogueoflife.org/dataset/2351/taxon/4LQWC

Or here as UI links to Checklist Bank:
https://data.catalogueoflife.org/dataset/2242/taxon/4LQWC
https://data.catalogueoflife.org/dataset/2296/taxon/4LQWC
https://data.catalogueoflife.org/dataset/2303/taxon/4LQWC
https://data.catalogueoflife.org/dataset/2315/taxon/4LQWC
https://data.catalogueoflife.org/dataset/2328/taxon/4LQWC
https://data.catalogueoflife.org/dataset/2332/taxon/4LQWC
https://data.catalogueoflife.org/dataset/2344/taxon/4LQWC
https://data.catalogueoflife.org/dataset/2349/taxon/4LQWC
https://data.catalogueoflife.org/dataset/2351/taxon/4LQWC

None of the releases contains `4LQWB`:
https://api.catalogueoflife.org/dataset/2242/taxon/4LQWB
https://api.catalogueoflife.org/dataset/2296/taxon/4LQWB
https://api.catalogueoflife.org/dataset/2303/taxon/4LQWB
https://api.catalogueoflife.org/dataset/2315/taxon/4LQWB
https://api.catalogueoflife.org/dataset/2328/taxon/4LQWB
https://api.catalogueoflife.org/dataset/2332/taxon/4LQWB
https://api.catalogueoflife.org/dataset/2344/taxon/4LQWB
https://api.catalogueoflife.org/dataset/2349/taxon/4LQWB
https://api.catalogueoflife.org/dataset/2351/taxon/4LQWB

**Comment by mdoering** [comment]
See also https://www.catalogueoflife.org/2020/12/18/infrastructure-live and https://www.catalogueoflife.org/2021/04/14/stable-ids

**Comment by mdoering** [comment]
Ah sorry. `4LQWC` is the id for the accepted name `Pomatomus saltatrix`
while `4LQWB` is the id for the synonym `Pomatomus saltator` which was the original query:

https://data.catalogueoflife.org/dataset/2242/taxon/4LQWB
https://data.catalogueoflife.org/dataset/2296/taxon/4LQWB
https://data.catalogueoflife.org/dataset/2303/taxon/4LQWB
https://data.catalogueoflife.org/dataset/2315/taxon/4LQWB
https://data.catalogueoflife.org/dataset/2328/taxon/4LQWB
https://data.catalogueoflife.org/dataset/2332/taxon/4LQWB
https://data.catalogueoflife.org/dataset/2344/taxon/4LQWB
https://data.catalogueoflife.org/dataset/2349/taxon/4LQWB
https://data.catalogueoflife.org/dataset/2351/taxon/4LQWB

The synonym ID still exists in all releases. But it seems our portal does not accept synonym ids but requires taxa.
@thomasstjerne can we please also resolve synonym IDs in the portal and redirect them to the respective taxon page?

**Comment by dshorthouse** [comment]
Thanks @mdoering @tomasstjerne for looking into this. I believe resolution of these synonym IDs worked in the past & did in fact redirect to the taxon page. So, restoring that behaviour would be most appreciated.
