### ISSUE TITLE
new datasources of fungal names

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnverifier#99]
As  in #62 and #81, I would suggest adding some more optional datasources for fungi.

- [MycoBank](https://www.mycobank.org) (excel releases in https://www.mycobank.org/images/MBList.zip)
- [Fungal Names](https://nmdc.cn/fungalnames) (txt releases in https://nmdc.cn/fungalnames/released)

Current [gnames version](https://verifier.globalnames.org/data_sources/5) of [_Species Fungorum_](http://www.speciesfungorum.org/) is already two years old. 
No idea of how frequently they incorporate new names, but that's not the only available repository: see "[_MycoBank_, _Index Fungorum_, and _Fungal Names_ recommended as official nomenclatural repositories for 2013](https://doi.org/10.1007/BF03449512)" for details.

Today I saw a draft paper proposing new fungi species and MycoBank was the nomenclatural repository used as a reference for them.
 
Thanks!
@abubelinha

**Comment by dimus** [comment]
Thank you @abubelinha, I will definitely investigate, and you are right it is nice to have both MycoBank and FungalNames in.

We are making a big hardware change this Friday and expanding storage capacity for our group, in particular it will affect where do I keep data-sources. Because of that I did postpone winter data update until next week. So your request came at a good time. Hopefully, I will be able to have both of these sources added next week.

**Comment by dimus** [comment]
Both sources are live now
